### ISSUE TITLE
What are the white artifacts in the sky?

### ISSUE THREAD

**Issue by wearhere** [gonsolo/gonzales#1]
The image at https://gonsoloblog.wordpress.com/2021/01/14/rendering-moana-with-swift/ shows white quads in the sky that don't seem to fit the scene. Where do they come from?

**Comment by gonsolo** [comment]
Short answer: Area lights.
Long answer: While I could make them invisible the (PBRT) scene as provided looks like this. You could add a completely transparent material for them. I just was too lazy.
