### ISSUE TITLE
How can this be built with Xcode 11.3?

### ISSUE THREAD

**Issue by azav** [gonsolo/gonzales#2]
In package.swift, the package `name:` parameter generates an error and must be removed before building.

The version of "https://github.com/kelvin13/png.git" must be changed to "3.0.0".

But then when built in the terminal, the following errors appear.

'PNG' Developer/gonzales-main/.build/checkouts/png: error: executable product 'unit-test' should have exactly one executable target
'PNG' Developer/gonzales-main/.build/checkouts/png: error: executable product 'integration-test' should have exactly one executable target

**Comment by gonsolo** [comment]
Package.swift starts with `//swift-tools-version:5.3` which is included in Xcode 12. I didn't test Xcode 11.
I just tried on Xcode 12.3 and it built fine. You have to have OpenEXR and Ptex installed in /usr/local though. I should add a check for this.

**Comment by azav** [comment]
How can I install those?  I checked on MacPorts and they aren't available.  I'm currently trying to build it on a Xeon Mac Pro with 12 cores and 64 GB of RAM.  Because of some older apps, I'm not able to update the OS past 10.14.6 and that limits it to Xcode 11.3.

**Comment by azav** [comment]
FYI, I `changed //swift-tools-version:5.3` to a version that will work with Xcode 11.3.

**Comment by gonsolo** [comment]
> How can I install those?

I installed them via Homebrew.
https://formulae.brew.sh/formula/openexr
https://formulae.brew.sh/formula/ptex#default

There are a few possibilities:
1. You can adapt Package.swift for Xcode 11 but I can't help you with the errors as I don't have that version installed.
2. Download Swift 5.3 and build on the command line.
3. Remove the dependency on PNG and try to build. Only the sky in the Moana scene is a png.
